StackOverflowAPI/urls.py
from django.contrib import admin
from django.conf.urls import include, url

urlpatterns = [
    url('admin/', admin.site.urls, name='admin'),
    url(r'^api-auth/', include('rest_framework.urls',
                               namespace='rest_framework')),
    url(r'^v1/app1/', include(('app_1_rest_api_only.urls', 'assignment_1'), namespace='app_1')),
    url(r'^v1/app2/', include(('app_2_with_angularjs.urls', 'assignment_2'), namespace='app_2')),
]

app_1_rest_api_only/urls.py
from django.conf.urls import url
from app_1_rest_api_only.views import StackApiQuestionsView

urlpatterns = [
    url(r'stackApi/', StackApiQuestionsView.as_view(), name='stack_api')
]

app_2_with_angularjs/urls.py
from django.conf.urls import url
from app_2_with_angularjs.views import StackTemplateViewSet


urlpatterns = [
    url(r'stackHome/', StackTemplateViewSet.as_view(), name='app2_home'),
]

app_1_rest_api_only/models.py
from django.db import models

# Create your models here.

app_2_with_angularjs/models.py
from django.db import models

# Create your models here.

app_1_rest_api_only/views.py
from django.core.cache import cache
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.permissions import AllowAny
from rest_framework.exceptions import Throttled
from rest_framework.status import (
    HTTP_201_CREATED, HTTP_200_OK, HTTP_400_BAD_REQUEST,
)
from StackOverflowAPI.utils import (
  AnonymousPerDayThrottle, AnonymousPerMinThrottle, CustomPagination
)
from stackapi import StackAPI
import time
import datetime


class StackApiQuestionsView(APIView):
    permission_classes = [AllowAny, ]
    pagination_class = CustomPagination
    throttle_classes = [
        AnonymousPerDayThrottle, AnonymousPerMinThrottle
    ]
    # helping function for throttle exceed message

    def throttled(self, request, wait):
        raise Throttled(detail={
            "message": "request limit exceeded",
            "availableIn": f"{wait} seconds",
            "throttleType": "Anonymous User "
        })

    def get(self, request):
        context = {
            'data': 'noting here'
        }

        return Response(context, status=HTTP_200_OK)

    def post(self, request):
        requested_data = request.data['data']
        # converting date into timestamp
        requested_data.update({'fromdate': int(str(time.mktime(
          datetime.datetime.strptime(requested_data['fromdate']
                                     , "%d/%m/%Y").timetuple())
                                    ).split('.')[0])})
        requested_data.update({'todate': int(str(time.mktime(
          datetime.datetime.strptime(requested_data['todate']
                                     , "%d/%m/%Y").timetuple())
                                    ).split('.')[0])})
        if requested_data['max'] is None:
            requested_data.pop('max')
        if requested_data['min'] is None:
            requested_data.pop('min')
        number_of_results = requested_data.pop('number_of_results')
        intagg_string = 'in' + '-' + ";".join(requested_data['tagged'])
        ex_tagg_string = 'ex'+'-'+';'.join(requested_data['nottagged'])
        other_string = "-".join([str(i) for i in requested_data.values()
                                 if type(i) is not list ])
        result_string = 'results'+'-' + str(number_of_results) if type(
              number_of_results) is int else '10'
        cache_key = intagg_string+ex_tagg_string+other_string+result_string
        cache_time = 86400
        data = cache.get(cache_key)
        context = {
          'message': 'data cached ',
          'data': []
        }
        if data:
            context.update({'data': data})
            return Response(context, status=HTTP_200_OK)
        else:
            api_obj = StackAPI('stackoverflow')
            # 10 result by default

            api_obj.max_pages = 1
            api_obj.page_size = 10
            if number_of_results is not None:
                api_obj.max_pages = number_of_results//10
            if 'tagged' in requested_data:
                requested_data.update({'tagged': ";".join(
                  sorted(requested_data['tagged'][:4]))})
            if 'nottagged' in requested_data:
                requested_data.update({'nottagged': ";".join(
                  sorted(requested_data['nottagged'][:4]))})
            try:
                if requested_data['order'] == 'ascending':
                    requested_data.pop('order')
                else:
                    requested_data.update({'order': 'desc'})
                question_req = api_obj.fetch('questions', **requested_data)
                cache.set(cache_key, question_req, cache_time)
                context.update({'message': 'data fetched successfully',
                                'data': question_req})
                return Response(context, status=HTTP_201_CREATED)
            except:
                context.update({'message': 'request error form StackAPi'})
                return Response(context, status=HTTP_400_BAD_REQUEST)

app_2_with_angularjs/views.py
from django.views.generic import TemplateView


class StackTemplateViewSet(TemplateView):
    template_name = "index.html"

app_2_with_angularjs/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

        <title>{% block title%}{% endblock%}</title>
        <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.9/angular.min.js"></script>

        <style type="text/css">

        </style>
      </head>
  <body>
      <section class="container">
          <div class="column is-two-thirds">
            {% include 'messages.html' %}
            {% block content %}
            {% endblock %}
           </div>
       </section>
      {% block js %}
      {% endblock %}
    </body>
</html>

app_2_with_angularjs/templates/index.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %} Homepage {% endblock %}
{% block content %}
<script src="{% static 'js/dirPagination.js' %}"></script>
<script>
    var app = angular.module("myApp", ['angularUtils.directives.dirPagination']);
    app.config(['$httpProvider', function ($httpProvider) {
        $httpProvider.defaults.xsrfCookieName = 'csrftoken';
        $httpProvider.defaults.xsrfHeaderName = 'X-CSRFToken';
    }]);
    app.config(function ($interpolateProvider) {
        $interpolateProvider.startSymbol('{$');
        $interpolateProvider.endSymbol('$}');
    });
    app.controller("appController", function (
        $scope, $http, $filter) {
        $scope.included_tags = [];
        $scope.excluded_tags = [];
        $scope.obtained_data = null;
        $scope.current_div = false;
        $scope.searchText='';
        $scope.intitle = '';
        $scope.sort = '';
        $scope.order = '';
        $scope.min = null;
        $scope.max = null;
        $scope.number_of_results = null;
        $scope.current_in_tag = '';
        $scope.current_ex_tag = '';
        $scope.fromdate = null;
        $scope.todate = null;
        $scope.currdate = new Date();
        $scope.yesterday = $scope.currdate - 1000 * 60 * 60 * 24;
        $scope.yesterday = new Date($scope.yesterday);
        $scope.refresh_page = function() {
            window.location.reload()
         }
        $scope.removeADDTag = function(tag) {
            var index = $scope.included_tags.indexOf(tag);
            $scope.included_tags.splice(index, 1);
        }
        $scope.removeExTag = function(tag) {
            var index = $scope.excluded_tags.indexOf(tag);
            $scope.excluded_tags.splice(index, 1);
        }
        $scope.onAddTags = function(tag) {
          $scope.included_tags.push(tag);
          $scope.current_in_tag = '';
        }
        $scope.onAddExTags = function(tag) {
          $scope.excluded_tags.push(tag);
          $scope.current_ex_tag = '';
        }

        $scope.form_submit = function() {
		        $http({
			      method: 'POST',
			      url: `{% url 'app_1:stack_api' %}`,
			      data: {"data": {'tagged':$scope.included_tags,
			                      'nottagged': $scope.excluded_tags,
			                      'intitle': $scope.intitle,
			                      'sort': $scope.sort,
			                      'order': $scope.order,
			                      'min': $scope.min,
			                      'max': $scope.max,
			                      'number_of_results': $scope.number_of_results,
			                      'fromdate': $filter('date')(
                                        $scope.fromdate, "dd/MM/yyyy"),
			                      'todate': $filter('date')(
                                        $scope.todate, "dd/MM/yyyy"),
			      }
			             }
		      }).then(function success(response) {
              if (response.status === 201) {
                  alert('data fetched successfully !!!');
                  console.log(response.data)
                  $scope.obtained_data = response.data['data']['items'];
                  console.log($scope.obtained_data);
               }
               else if (response.status === 200 ) {
                  alert('data cached successfully !!');
                  console.log(response.data)
                  $scope.obtained_data = response.data['data']['items'];
                }
               else {
                  alert("Sorry something went wrong");
               }
             }, function error(response) {
                if (response.status === 429 ) {
                  alert('Request limit exceeded , Try after sometime !!');
                }
              }
             );
	      }
    });
</script>

<section ng-app="myApp" ng-controller="appController">
  <div ng-show='!obtained_data'>
    <h2 class="center_align jumbotron">Welcome to StackAPI</h2>
    <form  class='mt-3'>
      <label>Included Tags: </label>
      <div
           ng-repeat="tag in included_tags">
          <button class="btn btn-success m-1"
          style="display:inline">
                              {$ tag $}
                <button type="button" class="close" aria-label="Close"
                  ng-click="removeADDTag(tag)">
                    <span aria-hidden="true">&times;</span>
                </button>
          </button>
      </div>
      <input type="text" ng-model='current_in_tag' value=""
             placeholder="Enter tag name to add"
      class="form-control mt-2">
      <button class="btn btn-primary mt-1" ng-click="onAddTags(current_in_tag)">Add </button>
      <br>
      <label >Excluded Tags: </label>
      <div
           ng-repeat="tag in excluded_tags">
          <button class="btn btn-success"
          style="display:inline">
                              {$ tag $}
                <button type="button" class="close" aria-label="Close"
                  ng-click="removeExTag(tag)">
                    <span aria-hidden="true">&times;</span>
                </button>
          </button>
      </div>
      <input type="text" ng-model='current_ex_tag' value=""
             class="form-control"
             placeholder="Enter tag name to add">
      <button class="btn btn-primary" ng-click="onAddExTags(current_ex_tag)">Add </button>

      <br>
      <label >Title Contains </label>
      <input type="text" name="number of results" class="form-control" value=""
             ng-model="intitle"
             placeholder="Enter a text that includes in title" >
      <label for="">From Date</label>
      <input class="form-control" type="date"
             ng-model="fromdate"
             ng-init="fromdate=yesterday">
      <br>
      <label for="">End Date</label>
      <input class="form-control" type="date"
             ng-model="todate"
             ng-init="todate=currdate">
      <label>Sort According to : <br/>
          <select
                  ng-options="x for x in ['activity', 'votes', 'creation', 'relevance']"
                  class="form-control"
                  ng-init="sort='votes'"
                  ng-model="sort">
          </select>
      </label>
      <label>Order According to : <br/>
          <select
                  ng-options="x for x in  ['ascending', 'descending']"
                  class="form-control"
                  ng-init="order='ascending'"
                  ng-model="order">
          </select>
      </label>
      <br>
      <label for="">Min</label>
      <input type="number" ng-model="min">
      <label for="">Max</label>
      <input type="number" ng-model="max">
      <br>
      <label for="">No of Results</label>
      <input type="number" ng-model="number_of_results" placeholder="should be divided by 10">
      <br>
      <button class="btn btn-primary" type="submit"
        ng-click="form_submit()"
      >Submit</button>
    </form>
  </div>

  <div ng-show="obtained_data">
       <h3 class="jumbotron center_align"> Requested data </h3>
        <button
        class="btn btn-success m-1"
        ng-click="refresh_page()"
        >Homepage</button>
        <div>
          <input type="text" ng-model="searchText"
                 placeholder="Search"
                 class="form-control">
          <table class="table table-hover">
            <br>
            <tr >
                <th>Sr.no</th>

                <th ng-click="order_key='title'; reverseSort=!reverseSort">Title </th>
                <th>Link</th>
                <th ng-click="order_key='is_answered'; reverseSort=!reverseSort">Answered</th>
                <th ng-click="order_key='score'; reverseSort=!reverseSort">Score</th>
                <th ng-click="order_key='owner_name'; reverseSort=!reverseSort">Owner Name</th>
                <th>Owner Link</th>
                <th> view more</th>

            </tr>
            <tr dir-paginate='data in obtained_data |itemsPerPage:10 |filter:searchText | orderBy: order_key:reverseSort'>
                <td>{$ $index+1 $}</td>
                <td>{$data['title']$}</td>
                <td><a href="{$ data['link'] $}">Questing link</a></td>
                <td>{$data['is_answered']$}</td>
                <td>{$data['score']$}</td>
                <td>{$data['owner']['owner_name']$}</td>
                <td><a href="{$ data['owner']['link'] $}">Link</a></td>
                <td>
                  <button class="btn btn-primary"
                  ng-click="current_div=true"
                  ng-show="!current_div"
                  >
                    view more
                  </button>
                  <div ng-show="current_div">
                    <img src="{$ data['owner']['profile_image'] $}" alt="no img found"
                    height="200px"; width="200px"
                    >
                    <label for="">Display name :</label>{$data['owner']['display_name']$}
                    <br>
                    <label for="">Reputation :</label>{$data['owner']['reputation']$}
                    <br>
                    <label for="">Accept rate :</label>{$data['owner']['accept_rate']$}
                    <br>
                    <label for="">Answer Count :</label>{$data['owner']['answer_count']$}
                    <br>
                    <label for="">Tags</label>{$data['tags']$}
                    <button class="btn btn-primary" ng-click="current_div=false">hide</button>
                  </div>
                </td>
            </tr>
      </table>
      <br>
    <div align="center">
           <dir-pagination-controls
                max-size="100"
                direction-links="true"
                boundary-links="true" >
           </dir-pagination-controls>
    </div>
        </div>
  </div>
</section>

{% endblock %}

app_2_with_angularjs/templates/messages.html
{% for message in messages %}
  <div class="alert {{ message.tags }} alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    {{ message }}
  </div>
{% endfor %}